#!/bin/sh

# This script backs up some important stuff
# This is the version for my home server

# force script to run as specific user
if [ "$(id -u)" -eq 0 ]; then
    exec sudo -H -u sintan $0 "$@"
fi

# Exit the whole script when ctrl+c is pressed
set -e

# Run only one instance of this script at one time
[ "${BKLOCKER}" != "running" ] && exec env BKLOCKER="running" flock -en "/tmp/impfilesbk.lock" "$0" "$@" || :

# Setup location for home and backup directory
HMDIR="/home/sintan"
BKDIR="/mnt/storage"

echo $(date) "| Backing up PhotoPrism index..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/photoprism/storage/index-backup.sql" "$BKDIR/Programs/Docker/PhotoPrism/index-backup-"$(date +%A)".sql" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up arr index..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/arr/config_sonarr/Backups/" "$BKDIR/Programs/Docker/arr-backups/sonarr/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/arr/config_prowlarr/Backups/" "$BKDIR/Programs/Docker/arr-backups/prowlarr/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up qBittorrent config..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/qbt/qbt-config/" "$BKDIR/Programs/Docker/qBittorrent-config/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/qbt-private/qbt-config/" "$BKDIR/Programs/Docker/qBittorrent2-config/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Caddyfiles..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/caddy/Caddyfiles/" "$BKDIR/Programs/Docker/Caddyfiles/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up cloudfalred config..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/cloudflared/config/" "$BKDIR/Programs/Docker/cloudflared-config/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up gpodder2go config..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/gpodder/data/" "$BKDIR/Programs/Docker/gpodder2go-data/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Navidrome db..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/navidrome/data/navidrome.db" "$BKDIR/Programs/Docker/navidrome.db" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Jellyfin config..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/jellyfin/config/" "$BKDIR/Programs/Docker/jellyfin-config/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Forgejo data..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Docker/forgejo/*-data" "$BKDIR/Programs/Docker/forgejo/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Docker compose files..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats --prune-empty-dirs -f '- /*/*/' "$HMDIR/Docker/" "$BKDIR/Programs/Docker/DockerCompose/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Pictures..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/Pictures/" "$BKDIR/Pictures/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/TempStorage/DCIM/" "$BKDIR/TempStorage/DCIM/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up Videos..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats --prune-empty-dirs -f '- /*/*/' "$HMDIR/Videos/" "$BKDIR/Videos/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo $(date) "| Backing up some dotfiles..." | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats --quiet --no-links --exclude={'*cache*','*Cache*'} --delete-excluded "$HMDIR/.config/" "$BKDIR/dotfiles/server/[dot]config/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/.bash_profile" "$BKDIR/dotfiles/server/[dot]bash_profile" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/.bashrc" "$BKDIR/dotfiles/server/[dot]bashrc" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
# rsync -aAXH --delete --stats "$HMDIR/.Xresources" "$BKDIR/dotfiles/server/[dot]Xresources" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
# rsync -aAXH --delete --stats "$BKDIR/dotfiles/[dot]local_bin_personal/" "$HMDIR/.local/bin/personal/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
rsync -aAXH --delete --stats "$HMDIR/.ssh/" "$BKDIR/dotfiles/server/[dot]ssh/" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo $'\n'$(date) "| Done!" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo "--- Now backing up to the DAS ---"
echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

HMDIR=/mnt/storage
BKDIR_P=/tank1/personal
BKDIR_M=/tank1/media

rsync -aAXH "$HMDIR/Pictures/" "$BKDIR_P/Pictures/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Videos/" "$BKDIR_P/Videos/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Academics/" "$BKDIR_P/Academics/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Zotero/" "$BKDIR_P/Zotero/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Code/" "$BKDIR_P/Code/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/TempStorage/DCIM/" "$BKDIR_P/TempStorage/DCIM/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/TempStorage/MobileSS/" "$BKDIR_P/TempStorage/MobileSS/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Programs/" "$BKDIR_P/Programs/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/dotfiles/" "$BKDIR_P/dotfiles/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Music/" "$BKDIR_M/Music/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"
rsync -aAXH "$HMDIR/Movies/" "$BKDIR_M/Movies/" | tee -a "$HMDIR/TempStorage/impfilesbk.log"

echo $'\n'"--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" | tee -a "$BKDIR/TempStorage/impfilesbk.log"
echo "--------------------------------------------------" | tee -a "$BKDIR/TempStorage/impfilesbk.log"

# Make the new files visible over samba
# chcon -R -t samba_share_t /mnt/storage/Programs/
# chcon -R -t samba_share_t /mnt/storage/dotfiles/server/
