#!/bin/sh

# This simply makes backup of file(s) as filename.bak

if [ $# -ge 1 ]; then
    for f in $@
    do
        [ -f "$f" ] && cp "$f"{,.bak}
    done
else
    echo "No filenames passed."
    exit 1
fi
