#!/bin/sh

DIR="/home/sintan/Documents/Backup"

echo "Movies"$'\n'"-------------------------------" > $DIR/movielist
ls /mnt/server/Movies/ >> $DIR/movielist
echo "-------------------------------"$'\n'"Movies Extra"$'\n'"-------------------------------" >> $DIR/movielist
ls "/mnt/server/Movies Extra/" >> $DIR/movielist