#!/bin/sh

# It makes the parent folders (if needed) while touch-ing.

if [ $# -ge 1 ]; then
    for f in $@
    do
        mkdir -p "$(dirname "$f")"
        touch "$f"
    done
else
    echo "No filenames passed."
fi
