#!/bin/sh

# It makes the parent folders (if needed) while touch-ing.

if [ $# -ge 1 ]; then
    for f in "$@"
    do
        echo "$f"
        mkdir -p "$(dirname "$f")"
        touch "$f"
    done
else
    echo "No filenames passed."
    exit 1
fi
